// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// RedSVD_matrix
SEXP RedSVD_matrix(SEXP Rm, int rank = 0);
RcppExport SEXP Redsvd_RedSVD_matrix(SEXP RmSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< int >::type rank(rankSEXP );
        SEXP __result = RedSVD_matrix(Rm, rank);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// RedSVD_dgCMatrix
SEXP RedSVD_dgCMatrix(SEXP Rm, int rank = 0);
RcppExport SEXP Redsvd_RedSVD_dgCMatrix(SEXP RmSEXP, SEXP rankSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type Rm(RmSEXP );
        Rcpp::traits::input_parameter< int >::type rank(rankSEXP );
        SEXP __result = RedSVD_dgCMatrix(Rm, rank);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
