# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
RedSVD.matrix <- function(Rm, rank = 0L) {
    .Call('Redsvd_RedSVD_matrix', PACKAGE = 'Redsvd', Rm, rank)
}

#'@export
RedSVD.dgCMatrix <- function(Rm, rank = 0L) {
    .Call('Redsvd_RedSVD_dgCMatrix', PACKAGE = 'Redsvd', Rm, rank)
}

